# 分布式微服务架构平台配置文件

# API网关配置
api_gateway:
  server:
    host: "0.0.0.0"
    port: 8080
    read_timeout: 30s
    write_timeout: 30s
    idle_timeout: 60s
  
  registry:
    endpoints:
      - "localhost:2379"
    timeout: 5s
  
  rate_limit:
    enabled: true
    requests_per_second: 100
    burst: 200
  
  log:
    level: "info"
    format: "json"
    output: "stdout"
  
  services:
    user_service: "user-service"
    order_service: "order-service"
    payment_service: "payment-service"

# 用户服务配置
user_service:
  server:
    host: "0.0.0.0"
    port: 8081
    read_timeout: 30s
    write_timeout: 30s
    idle_timeout: 60s
  
  service:
    name: "user-service"
    version: "v1.0.0"
    tags:
      - "user"
      - "auth"
  
  database:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "password"
    dbname: "microservice_user"
    sslmode: "disable"
    timezone: "Asia/Shanghai"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s
  
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    pool_size: 10
    min_idle_conns: 5
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    pool_timeout: 4s
    idle_timeout: 300s
  
  registry:
    endpoints:
      - "localhost:2379"
    timeout: 5s
  
  log:
    level: "info"
    format: "json"
    output: "stdout"
    caller: true
  
  jwt:
    secret_key: "your-secret-key-here"
    token_duration: 24h

# 订单服务配置
order_service:
  server:
    host: "0.0.0.0"
    port: 8082
    read_timeout: 30s
    write_timeout: 30s
    idle_timeout: 60s
  
  service:
    name: "order-service"
    version: "v1.0.0"
    tags:
      - "order"
      - "business"
  
  database:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "password"
    dbname: "microservice_order"
    sslmode: "disable"
    timezone: "Asia/Shanghai"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s
  
  redis:
    addr: "localhost:6379"
    password: ""
    db: 1
    pool_size: 10
    min_idle_conns: 5
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    pool_timeout: 4s
    idle_timeout: 300s
  
  registry:
    endpoints:
      - "localhost:2379"
    timeout: 5s
  
  log:
    level: "info"
    format: "json"
    output: "stdout"
    caller: true

# 支付服务配置
payment_service:
  server:
    host: "0.0.0.0"
    port: 8083
    read_timeout: 30s
    write_timeout: 30s
    idle_timeout: 60s
  
  service:
    name: "payment-service"
    version: "v1.0.0"
    tags:
      - "payment"
      - "financial"
  
  database:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "password"
    dbname: "microservice_payment"
    sslmode: "disable"
    timezone: "Asia/Shanghai"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s
  
  redis:
    addr: "localhost:6379"
    password: ""
    db: 2
    pool_size: 10
    min_idle_conns: 5
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    pool_timeout: 4s
    idle_timeout: 300s
  
  registry:
    endpoints:
      - "localhost:2379"
    timeout: 5s
  
  log:
    level: "info"
    format: "json"
    output: "stdout"
    caller: true

# 全局配置
global:
  # 环境配置
  environment: "development" # development, testing, production
  
  # 监控配置
  monitoring:
    prometheus:
      enabled: true
      port: 9090
      path: "/metrics"
    
    jaeger:
      enabled: true
      endpoint: "http://localhost:14268/api/traces"
      service_name: "micro-service-platform"
  
  # 安全配置
  security:
    cors:
      enabled: true
      allowed_origins:
        - "http://localhost:3000"
        - "http://localhost:8080"
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allowed_headers:
        - "Content-Type"
        - "Authorization"
        - "X-Requested-With"
      max_age: 86400
    
    rate_limit:
      global_limit: 1000
      per_ip_limit: 100
      window: "1m"