server:
  port: 8080
  host: "0.0.0.0"
  mode: "debug"

etcd:
  endpoints:
    - "localhost:2379"
  timeout: 5

services:
  user-service:
    name: "user-service"
    timeout: 30
  order-service:
    name: "order-service"
    timeout: 30
  payment-service:
    name: "payment-service"
    timeout: 30

log:
  level: "info"
  format: "json"
  output: "stdout"

gateway:
  name: "api-gateway"
  version: "v1.0.0"
  id: "api-gateway-1"

rate_limit:
  enabled: true
  requests_per_second: 100
  burst: 200