server:
  port: 8081
  host: "0.0.0.0"
  mode: "debug"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "user_service"
  sslmode: "disable"
  timezone: "Asia/Shanghai"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

etcd:
  endpoints:
    - "localhost:2379"
  timeout: 5

jwt:
  secret: "your-secret-key"
  expire_hours: 24

log:
  level: "info"
  format: "json"
  output: "stdout"

service:
  name: "user-service"
  version: "v1.0.0"
  id: "user-service-1"